### ISSUE TITLE
Can't we get away the manual post-update-hook by changing the install dir?

### ISSUE THREAD

**Issue by DasNaCl** [Evidlo/remarkable_entware#11]
Why is everything installed under `/opt` and not locally in `/home/root`?

**Comment by Evidlo** [comment]
@DasNaCl I'm not super familiar with the internals of Entware, but I think I remember many of the Entware binaries being hardcoded to look in /opt.

And technically everything is in `/home/root/.entware`, as mentioned in the readme.
