### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Eeems** [Evidlo/remarkable_entware#13]
What is this licensed under? I just see a copyright in the code.

**Comment by saxbophone** [comment]
+1 on this. Explicitly providing a software license helps other developers who might want to make use of this project, send improvements or propose new features, know clearly under what terms the source code is distributed. Without a license, as per Github's terms of service, we only technically have the right to download, fork and study the code...

**Comment by saxbophone** [comment]
Closed in e91649261750f0f53cccde952d03e1140247c511
