### ISSUE TITLE
Instructions to reset after a failed install?

### ISSUE THREAD

**Issue by kubycsolutions** [Evidlo/remarkable_entware#25]
My first attempt to run the installer glitched for some reason, on my RM3 running 3.9.something. Attempting to re-run it, I'b being told `Error: Folder /opt exists! Quitting...`

If I attempt to `rm -rf /opt`, I'm told `rm: can't remove '/opt': Device or resource busy`

Rebooting the ReMarkable does not solve this; I'm still told /opt is busy.

`ls -al /opt` shows it as empty.

How can I reset in order to run a fresh install attempt?

(For context: What I'm trying to do is fill in some of the things that `codexctl` apparently has as prerequisites, so I can use it to roll back far enough to install `toltec`...

**Comment by travist85** [comment]
@kubycsolutions You can't delete /opt because it is mounted during the install. You need to do the following before you run the installer again:
`umount /opt`
`rm -rf /opt`
`rm -rf /home/root/.entware`
