### ISSUE TITLE
Installer script doesn't have enough space to create /opt

### ISSUE THREAD

**Issue by CTXz** [Evidlo/remarkable_entware#6]
Hey

I'm attempting to install Entware on my reMarkable, running Version 1.8.1.1 and the installer complaints that `/opt` cannot be created due to insufficient space available.

```
remarkable: ~/ sh entware_install.sh 
Info: Checking for prerequisites and creating folders...
mkdir: can't create directory '/opt': No space left on device
Encountered error.  Cleaning up and quitting...
```

It seems that with the new update, 100% of the root partition is used:
```
remarkable: ~/ df -m /
Filesystem           1M-blocks      Used Available Use% Mounted on
/dev/root                  214       210         0 100% /
```

**Comment by CTXz** [comment]
This issue got resolved after I attempted to unsuccessfully exchange a few unused files in the rootfs with the /opt directory. Attempting this caused my rM to crash multiples times on boot (due to the device running out of memory), thus forcing it to change the rootfs to the reMarkables "second root" partition (thereby also resetting it). After switching to the second partition I had more than plenty of space to install entware.

@pciavald further elaborated to this on the reMarkable discord:
```
if you inspect the rM's partitions you will find it has 2 root partitions, which is common to embedded linux hardware. After a few uncorrect reboots it will change its root to the other partition. I've noticed that when trying to emulate the storage. Also seen this behaviour on DDWRT routers
```

Perhaps the script could somehow take this potential issue into account?

I presume it is fair to give this issue a low priority, as this seems to occur only on some devices.

**Comment by Evidlo** [comment]
What could be done about this? I found a bit more information [here](https://jumpnowtek.com/linux/An-upgrade-strategy-for-embedded-Linux-systems.html) about having two roots in Yocto.

The `uEnv.txt` file they refer to appears to be at `/var/lib/uboot/uboot.env`.  I feel like tampering with this file risks soft-bricking the device.

**Comment by Evidlo** [comment]
I'm closing this, as I don't think any further action should be taken by the installer.
