### ISSUE TITLE
Add binaries to PATH when using ssh

### ISSUE THREAD

**Issue by cloudsftp** [Evidlo/remarkable_entware#9]
It seems I can't change the `PATH` variable for ssh commands without login.
I added the line `PATH=/opt/bin:/opt/sbin:$PATH` to the `~/.bashrc` and when logged in this is displayed:
```
reMarkable: ~/ echo $PATH
/opt/bin:/opt/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
```

But when running the command without login this is displayed:
```
$ ssh root@$rssh_ip 'echo $PATH'
/usr/bin:/bin
```

I tried
- changing the line in the `~/.bashrc` to `export PATH=/opt/bin:/opt/sbin:$PATH`
- sourcing `~/.bashrc` in `~/.bash_profile`
- sourcing `~/.bashrc` in `/etc/bash.bashrc`

Can someone help?

**Comment by Evidlo** [comment]
What about sourcing the `.bashrc` in `.profile`?

**Comment by cloudsftp** [comment]
I tried, but no success.

Content of `.profile`:
```
$ ssh root@$rssh_ip 'cat ~/.profile'
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
```

If you meant `/etc/profile`, that file already sources `~/.bashrc`:
```
$ ssh root@$rssh_ip 'tail /etc/profile'
  esac
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

export PATH PS1 OPIEDIR QPEDIR QTDIR EDITOR TERM

umask 022
```

I also copied the content of `~/.profile` to
- `.bash_profile`
- `/etc/bash.bashrc`
and made sure they are all executable.

I also restarted my reMarkable before attempting to read the `PATH` variable via ssh again.

I am also using the reMarkable version 2, so maybe it doesn't work with the linux distribution that is installed there?

**Comment by Evidlo** [comment]
I don't think this issue is specific to entware or the reMarkable really.  Its more because ssh with a command argument doesn't start an interactive shell.

https://stackoverflow.com/questions/940533/how-do-i-set-path-such-that-ssh-userhost-command-works

**Comment by cloudsftp** [comment]
I tried moving the line, where the `PATH` variable is set, to the beginning.
But there is no check, whether the shell was started in interactive mode. So it had no effect sadly.

What I gathered from [this StackOverflow post](https://unix.stackexchange.com/questions/332531/why-does-remote-bash-source-bash-profile-instead-of-bashrc) is that `~/.bashrc` must be loaded when executing commands via ssh without login.
So it has to be a reMarkable issue.
I will contact the support team and report their take on the matter.

**Comment by raisjn** [comment]
iirc, @siraben ran into something like this and it was related to dropbear ssh

**Comment by siraben** [comment]
Yeah, I think it's due to the SSH on the device being dropbear, and so the various solutions on the internet only works for openssh. One possible fix would be to replace the SSH binary on the device with openssh.

**Comment by cloudsftp** [comment]
Ok, thank you. I probably will use a workaround, I don't want to accidentally screw my ssh access.

**Comment by siraben** [comment]
@cloudsftp Let me know what your workaround is for setting PATH correctly.

**Comment by raisjn** [comment]
can you run openssh on a different port?

**Comment by cloudsftp** [comment]
@siraben I actually work around the issue to set the `PATH` in the first place.
I simply hard code the commands like this `/opt/bin/head` instead of `head` in programs that need to execute such binaries via ssh.
Like [this](https://github.com/cloudsftp/reStream/commit/8ef5873894a594fbd977e5fece22781b350f2ba2).
